AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for deploying SET solver on AWS

Globals:
  Function:
    Timeout: 3

Resources:
  SetSolverGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - image~1jpeg
        - image~1jpg
  SetSolverFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        SetSolver:
          Type: Api 
          Properties:
            Path: /solve
            Method: post
            RestApiId: !Ref SetSolverGatewayApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.8-v1
